### ISSUE TITLE
Some questions about location information

### ISSUE THREAD

**Issue by MindaWu** [ngmsoftware/blender-kinect#1]
By looking at your source code, I learned that you are passing the location information  into the blender, and then calling the edit_bones function in the EDIT mode to rotate the bone. But using this method should be a requirement for the position of the human skeleton. In your code I also saw that you gave the location information to reset the position of the human skeleton. I am curious how you got this set of values?

**Comment by martinsallandm** [comment]
Hello there,

   About the EDIT mode, If I remember correctly I guess I did that because
I started putting constrains in the bone lengths so I could not put the
bones ends in any position... So in edit mode it seemed at the time I
could. But I dont remember exactly. The fact is that in the end, they
should be in POSE mode, so you can animate a rigged object.

   The values for the reset were just the values I aquired for an skeleton
offline (I did a function so save the current state in a file and them hard
coded the content in the source as a reset position).

Thanks for your question!

[]'s

**Comment by MindaWu** [comment]
Thank you very much for your answer. The current work I do is to apply the three-dimensional coordinate information of the bone (including the coordinate information collected by kinect but not limited to this) to the model in the blender. But by looking at your source code, I found that you have achieved a change in bone poses with the following code. But when I import a bone model myself and call this method to rotate the bone (in this case I am using my bone position information), it does not produce the effect. I am not very clear about where I did it wrong. Is your method required for the initial position of the model ? Is my understanding of your method of rotating bones wrong ?

'

     def kinectValuesToScene(self, joints):
      
        if not (joints is None):
            J = {}
            for i in range(0,25):
                J[NAMES[i]] = Vector( (float(joints[i]), float(joints[i+25]), float(joints[i+50])) )


            A = self._A
    
            bpy.ops.object.mode_set(mode='EDIT')    
            
            A.data.edit_bones['Head-Neck'].head = J['Head']
            A.data.edit_bones['Neck-SpineShoulder'].head = J['Neck']
            A.data.edit_bones['SpineShoulder-SpineMid'].head = J['SpineShoulder']
            A.data.edit_bones['SpineMid-SpineBase'].head = J['SpineMid']
            A.data.edit_bones['SpineBase-HipLeft'].head = J['SpineBase']

            A.data.edit_bones['SpineBase-HipRight'].head = J['SpineBase']
            A.data.edit_bones['SpineShoulder-ShoulderLeft'].head = J['SpineShoulder']

            A.data.edit_bones['SpineShoulder-ShoulderRight'].head = J['SpineShoulder']
            A.data.edit_bones['ShoulderLeft-ElbowLeft'].head = J['ShoulderLeft']
            A.data.edit_bones['ShoulderRight-ElbowRight'].head = J['ShoulderRight']
            A.data.edit_bones['ElbowLeft-WristLeft'].head = J['ElbowLeft']
            A.data.edit_bones['ElbowRight-WristRight'].head = J['ElbowRight']
            A.data.edit_bones['WristLeft-HandLeft'].head = J['WristLeft']
            A.data.edit_bones['WristRight-HandRight'].head = J['WristRight']
            A.data.edit_bones['HandLeft-HandTipLeft'].head = J['HandLeft']
            A.data.edit_bones['HandRight-HandTipRight'].head = J['HandRight']
            A.data.edit_bones['HandLeft-ThumbLeft'].head = J['HandLeft']
            A.data.edit_bones['HandRight-ThumbRight'].head = J['HandRight']

            A.data.edit_bones['HipLeft-KneeLeft'].head = J['HipLeft']
            A.data.edit_bones['HipRight-KneeRight'].head = J['HipRight']

            A.data.edit_bones['KneeLeft-AnkleLeft'].head = J['KneeLeft']
            A.data.edit_bones['KneeRight-AnkleRight'].head = J['KneeRight']
            A.data.edit_bones['AnkleLeft-FootLeft'].head = J['AnkleLeft']
            A.data.edit_bones['AnkleRight-FootRight'].head = J['AnkleRight']

            A.data.edit_bones['Head-Neck'].tail = J['Neck']
            A.data.edit_bones['Neck-SpineShoulder'].tail = J['SpineShoulder']
            A.data.edit_bones['SpineShoulder-SpineMid'].tail = J['SpineMid']
            A.data.edit_bones['SpineMid-SpineBase'].tail = J['SpineBase']
            A.data.edit_bones['SpineBase-HipLeft'].tail = J['HipLeft']

            A.data.edit_bones['SpineBase-HipRight'].tail = J['HipRight']
            A.data.edit_bones['SpineShoulder-ShoulderLeft'].tail = J['ShoulderLeft']

            A.data.edit_bones['SpineShoulder-ShoulderRight'].tail = J['ShoulderRight']
            A.data.edit_bones['ShoulderLeft-ElbowLeft'].tail = J['ElbowLeft']
            A.data.edit_bones['ShoulderRight-ElbowRight'].tail = J['ElbowRight']
            A.data.edit_bones['ElbowLeft-WristLeft'].tail = J['WristLeft']
            A.data.edit_bones['ElbowRight-WristRight'].tail = J['WristRight']
            A.data.edit_bones['WristLeft-HandLeft'].tail = J['HandLeft']
            A.data.edit_bones['WristRight-HandRight'].tail = J['HandRight']
            A.data.edit_bones['HandLeft-HandTipLeft'].tail = J['HandTipLeft']
            A.data.edit_bones['HandRight-HandTipRight'].tail = J['HandTipRight']
            A.data.edit_bones['HandLeft-ThumbLeft'].tail = J['ThumbLeft']
            A.data.edit_bones['HandRight-ThumbRight'].tail = J['ThumbRight']

            A.data.edit_bones['HipLeft-KneeLeft'].tail = J['KneeLeft']
            A.data.edit_bones['HipRight-KneeRight'].tail = J['KneeRight']

            A.data.edit_bones['KneeLeft-AnkleLeft'].tail = J['AnkleLeft']
            A.data.edit_bones['KneeRight-AnkleRight'].tail = J['AnkleRight']
            A.data.edit_bones['AnkleLeft-FootLeft'].tail = J['FootLeft']
            A.data.edit_bones['AnkleRight-FootRight'].tail = J['FootRight']
            bpy.ops.object.mode_set(mode='OBJECT')'

**Comment by MindaWu** [comment]
In other words, my doubt is that if I don't need real-time interaction between blender-kinect, but I already have three-dimensional coordinates of the bone, how can I rotate the skeleton of the model so that the pose is consistent with the pose expressed by the three-dimensional coordinate information? ? I tried to calculate Euler angles or called the API in the Blender model pose mode in the last few months, but it didn't work. When I saw your project, I was very excited but didn't quite understand the principle.

**Comment by martinsallandm** [comment]
Hello,

   My code position the joints in OBJECT space... To rig a character and
move it with the joints you need to change in POSE space. In the same box
that you go from "object mode" to "edit mode" you can go to "pose mode".
   So you have to make sure that the python code changes the POSE, not the
position of the bones. I don't remember how to do it, but you can google it
(should be straight forward).

[]'s

**Comment by MindaWu** [comment]
Thank you for your answer, although I still don't quite understand how you do it, and the operation of the code. But thank you very much for your patience. I am very encouraged after seeing your results.
